apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Dev Auth to overlay</title>
    </head>
    <body>

    <h1>Dev Auth Provider</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
