apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Windseeker </title>
    </head>
    <body>

    <h1>Windseeker Preprod Environment</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
